version: "3.8"

services:
  # Api
  bmxapi:
    image: bmxapi:latest
    container_name: bmxapi_container
    ports:
      - "5090:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  # Db MySql
  db:
    image: mysqlbmxdb:latest
    container_name: mysql_container_bmxdb
    restart: always
    ports:
      - "3309:3306"
