CREATE TABLE `bmxdb`.`Bike` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NULL,
    `Brand` VARCHAR(45) NULL,
    `Model` VARCHAR(45) NULL,
    `Color` VARCHAR(45) NULL,
    `Frame` VARCHAR(45) NULL,
    `Fork` VARCHAR(45) NULL,
    `Bars` VARCHAR(45) NULL,
    `Stem` VARCHAR(45) NULL,
    `Grips` VARCHAR(45) NULL,
    `Seat` VARCHAR(45) NULL,
    `SeatPost` VARCHAR(45) NULL,
    `Cranks` VARCHAR(45) NULL,
    `Pedals` VARCHAR(45) NULL,
    `Sprocket` VARCHAR(45) NULL,
    `FrontWheel` VARCHAR(45) NULL,
    `RearWheel` VARCHAR(45) NULL,
    `FrontTire` VARCHAR(45) NULL,
    `RearTire` VARCHAR(45) NULL,
    `FrontHub` VARCHAR(45) NULL,
    `RearHub` VARCHAR(45) NULL,
    `Chain` VARCHAR(45) NULL,
    `Pegs` VARCHAR(45) NULL,
    PRIMARY KEY (`Id`)
);

CREATE TABLE `bmxdb`.`User` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Username` VARCHAR(45) NOT NULL,
    `Email` VARCHAR(45) NOT NULL,
    `Password` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`Id`)
);

INSERT INTO `bmxdb`.`Bike` (
        `Name`,
        `Brand`,
        `Model`,
        `Color`,
        `Frame`,
        `Fork`,
        `Bars`,
        `Stem`,
        `Grips`,
        `Seat`,
        `SeatPost`,
        `Cranks`,
        `Pedals`,
        `Sprocket`,
        `FrontWheel`,
        `RearWheel`,
        `FrontTire`,
        `RearTire`,
        `FrontHub`,
        `RearHub`,
        `Chain`,
        `Pegs`
    )
VALUES (
        'Bike1',
        'Brand1',
        'Model1',
        'Color1',
        'Frame1',
        'Fork1',
        'Bars1',
        'Stem1',
        'Grips1',
        'Seat1',
        'SeatPost1',
        'Cranks1',
        'Pedals1',
        'Sprocket1',
        'FrontWheel1',
        'RearWheel1',
        'FrontTire1',
        'RearTire1',
        'FrontHub1',
        'RearHub1',
        'Chain1',
        'Pegs1'
    ),
    (
        'Bike2',
        'Brand2',
        'Model2',
        'Color2',
        'Frame2',
        'Fork2',
        'Bars2',
        'Stem2',
        'Grips2',
        'Seat2',
        'SeatPost2',
        'Cranks2',
        'Pedals2',
        'Sprocket2',
        'FrontWheel2',
        'RearWheel2',
        'FrontTire2',
        'RearTire2',
        'FrontHub2',
        'RearHub2',
        'Chain2',
        'Pegs2'
    ),
    (
        'Bike3',
        'Brand3',
        'Model3',
        'Color3',
        'Frame3',
        'Fork3',
        'Bars3',
        'Stem3',
        'Grips3',
        'Seat3',
        'SeatPost3',
        'Cranks3',
        'Pedals3',
        'Sprocket3',
        'FrontWheel3',
        'RearWheel3',
        'FrontTire3',
        'RearTire3',
        'FrontHub3',
        'RearHub3',
        'Chain3',
        'Pegs3'
    ),
    (
        'Bike4',
        'Brand4',
        'Model4',
        'Color4',
        'Frame4',
        'Fork4',
        'Bars4',
        'Stem4',
        'Grips4',
        'Seat4',
        'SeatPost4',
        'Cranks4',
        'Pedals4',
        'Sprocket4',
        'FrontWheel4',
        'RearWheel4',
        'FrontTire4',
        'RearTire4',
        'FrontHub4',
        'RearHub4',
        'Chain4',
        'Pegs4'
    );

INSERT INTO `bmxdb`.`User` (
        `Username`,
        `Email`,
        `Password`
    )
VALUES (
        'Hackerman',
        'Hackerman@gmail.com',
        'Hackerman12345@'
    ),
    (
        'User2',
        'Email2@gmail.com',
        'Password2'
    ),
    (
        'User3',
        'Email3@gmail.com',
        'Password3'
    ),
    (
        'User4',
        'Email4@gmail.com',
        'Password4'
    ),
    (
        'User5',
        'Email5@gmail.com',
        'Password5'
    );